import streamlit as st

st.set_page_config(page_title="Salesoes IA", layout="wide")

st.title("Dashboard Salesoes IA")
st.markdown("10 sectores priorizados para prospección, diagnóstico y automatización.")

# Datos de los 10 sectores
sectores = [
    {
        "sector_id": "01",
        "nombre": "Asesorías y Gestorías",
        "subsector": "Servicios Profesionales",
        "fit": "Muy alto",
        "tamano_mercado": "~27.000 asesorías",
        "facturacion_agregada": "~8.500M€/año",
        "adopcion_ia": "~35%",
        "top_problema": "Introducción manual de datos de clientes",
        "top_herramienta": "Fintonic Business",
        "top_objecion": "No tenemos presupuesto",
        "señal_prioridad": "Web moderna con portal del cliente",
    },
    {
        "sector_id": "02",
        "nombre": "Despachos de Abogados",
        "subsector": "Servicios Profesionales - Legal",
        "fit": "Muy alto",
        "tamano_mercado": "~140.000 abogados",
        "facturacion_agregada": "~12.000M€/año",
        "adopcion_ia": "~28%",
        "top_problema": "Búsqueda de jurisprudencia manual",
        "top_herramienta": "LegesAI",
        "top_objecion": "No tenemos presupuesto",
        "señal_prioridad": "Web moderna con portal del cliente",
    },
    {
        "sector_id": "03",
        "nombre": "Clínicas Dentales",
        "subsector": "Salud - Odontología",
        "fit": "Muy alto",
        "tamano_mercado": "~24.000 clínicas",
        "facturacion_agregada": "~1.305M€",
        "adopcion_ia": "~25%",
        "top_problema": "Agenda con huecos improductivos",
        "top_herramienta": "Overjet",
        "top_objecion": "La odontología es muy manual",
        "señal_prioridad": "Web moderna con cita online",
    },
    {
        "sector_id": "04",
        "nombre": "Clínicas Veterinarias",
        "subsector": "Salud - Veterinaria",
        "fit": "Alto",
        "tamano_mercado": "~7.032 clínicas",
        "facturacion_agregada": "~3.069M€/año",
        "adopcion_ia": "~15%",
        "top_problema": "Agenda con huecos improductivos",
        "top_herramienta": "SignalPET",
        "top_objecion": "La veterinaria es muy manual",
        "señal_prioridad": "Web moderna con cita online",
    },
    {
        "sector_id": "05",
        "nombre": "Inmobiliarias",
        "subsector": "Servicios - Inmobiliario",
        "fit": "Muy alto",
        "tamano_mercado": "~60.683 agencias",
        "facturacion_agregada": "~9.400M€/año",
        "adopcion_ia": "~20%",
        "top_problema": "Captación manual de propiedades",
        "top_herramienta": "Idealista AVM",
        "top_objecion": "El sector es muy relacional",
        "señal_prioridad": "Web moderna con buscador avanzado",
    },
    {
        "sector_id": "06",
        "nombre": "Hoteles",
        "subsector": "Hostelería - Alojamiento",
        "fit": "Muy alto",
        "tamano_mercado": "~14.613 hoteles",
        "facturacion_agregada": "~125.340M€",
        "adopcion_ia": "~25%",
        "top_problema": "Pricing estático o reactivo",
        "top_herramienta": "Duetto",
        "top_objecion": "El sector es muy tradicional",
        "señal_prioridad": "Web moderna con motor de reservas",
    },
    {
        "sector_id": "07",
        "nombre": "Apartamentos Turísticos",
        "subsector":
